RDKCOM-2118: REFPLTV-929 Build errors in xraudio-utils
| ../../../../../../../../rdk/components/generic/xraudio-utils/src/sounds.c: In function 'xraudio_utils_sound_play':
| ../../../../../../../../rdk/components/generic/xraudio-utils/src/sounds.c:92:36: error: too few arguments to function 'xraudio_object_create'
|     g_xraudio_utils_sounds.object = xraudio_object_create();
|                                     ^~~~~~~~~~~~~~~~~~~~~
| In file included from ../../../../../../../../rdk/components/generic/xraudio-utils/src/sounds.c:31:0:
| ../../../../../../../../rdk/components/generic/xraudio-utils/src/sounds.c: In function 'xraudio_utils_sound_play':
| ../../../../../../../../rdk/components/generic/xraudio-utils/src/sounds.c:146:114: error: passing argument 4 of 'xraudio_open' makes integer from pointer without a cast [-Werror=int-conversion]
|   146 |    result = xraudio_open(g_xraudio_utils_sounds.object, XRAUDIO_DEVICE_INPUT_NONE, XRAUDIO_DEVICE_OUTPUT_NORMAL, NULL);
|       |                                                                                                                  ^~~~
|       |                                                                                                                  |
|       |                                                                                                                  void *
| In file included from ../../../../../../../../rdk/components/generic/xraudio-utils/src/sounds.c:31:

Reason for change: REFPLTV-929 Build errors in xraudio-utils
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit eadd3d5a129182814e56cb8d4e3d180037dd722e)
Change-Id: I0dba0a4fd6a228755fa4b64c85a93c1e4a5be4d0